### ISSUE TITLE
Docs & Release notes for 4.0.0

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#3228]
- [x] Disable path transliteration (https://github.com/enonic/app-contentstudio/issues/3121)
- [x] Deprecated image component (https://github.com/enonic/app-contentstudio/issues/3215)
- [x] Responsive widget panel (https://github.com/enonic/app-contentstudio/issues/3226)
- [x] Bigger dropdowns (https://github.com/enonic/lib-admin-ui/issues/1993 https://github.com/enonic/app-contentstudio/issues/3213)
- [x] Content Archive (https://github.com/enonic/app-contentstudio/issues/3262)
- [x] Implement a new way of displaying inbound references in the Delete dialog (https://github.com/enonic/app-contentstudio/issues/3260)
- [x] Spellcheck support in TextLine and TextArea (https://github.com/enonic/app-contentstudio/issues/3155)
