### ISSUE TITLE
Release notes for 4.3.0

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#5139]
- [x] Insert Link dialog
- [x] New Project Wizard
- [x] Collaboration is always on
- [x] Version History improvements
- [x] `settings.hideDefaultProject` (and how it works in conjunction with the New Project Wizard)
- [x] RTL support
