### ISSUE TITLE
Content move improvements

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#6681]
```[tasklist]
### Tasks
- [ ] https://github.com/enonic/app-contentstudio/issues/6678
- [ ] https://github.com/enonic/app-contentstudio/issues/6762
- [ ] https://github.com/enonic/app-contentstudio/issues/6763
- [ ] https://github.com/enonic/app-contentstudio/issues/6764
```
