### ISSUE TITLE
Multi-inheritance

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#7103]
- [x] Revive the functionality in Content Studio (https://github.com/enonic/app-contentstudio/issues/7103)
- [x] Test Content Studio against [this branch](https://github.com/enonic/xp/tree/issue-10242) in XP:
  - [x] Multi-select parent in the New Project wizard
  - [x] Inheritance from multi-parents
  - [x] Project Graph in the Settings (created https://github.com/enonic/app-contentstudio/issues/7108)
- [x] Revive the Layers widget in Content Studio+ (https://github.com/enonic/app-contentstudio-plus/issues/1142)
- [x] Deploy both CS and CS+ to https://dev-branch-multi-inheritance.enonic.net/admin/tool
- [x] Inform @sigdestad that it's ready for testing
- [x] https://github.com/enonic/app-contentstudio/issues/7149

**Comment by alansemenov** [comment]
Issue for the project graph fixes: https://github.com/enonic/app-contentstudio/issues/7108
