### ISSUE TITLE
Replace ContentTreeGrid with new non-slickgrid classes

### ISSUE THREAD

**Issue by ashklianko** [enonic/app-contentstudio#7169]
Required functionality checklist:

```[tasklist]
### Tasks
- [ ] Tree like structure
- [ ] Lazy loading
- [ ] Hightlight/Selection functionality
- [ ] Server events handling
- [ ] Right click menu
- [ ] Refresh functionality
```
