### ISSUE TITLE
Support integration with Juke Translator

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#7668]
As a Content Editor, I want AI to assist me in translation of text fields in a content item localised inside a layer. I want to be able to verify the suggested translations before I save the result.

```[tasklist]
### Tasks
- [ ] https://github.com/enonic/app-contentstudio/issues/7669
- [ ] https://github.com/enonic/app-contentstudio/issues/7670
- [ ] https://github.com/enonic/app-contentstudio/issues/7671
- [ ] https://github.com/enonic/lib-admin-ui/issues/3635
```
